name: Install JDK
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install jdk
        run: |
          ID="1WAd6ESc_pJP8KRdcg6RbYRI4w6o1IbZ_"
          FILE="jdk-8u191-linux-x64.tar.gz"
          CONFIRM=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://drive.google.com/uc?export=download&id=$ID" -O- | sed -En 's/.*confirm=([0-9A-Za-z_]+).*/\1/p')
          wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$CONFIRM&id=$ID" -O $FILE
          sudo mkdir -p /usr/lib/jvm
          sudo tar zxvf $FILE -C /usr/lib/jvm
          sudo chown -R root:root /usr/lib/jvm/jdk1.8.0_191

          ls -l /usr/lib/jvm
          ls -l /usr/lib/jvm/jdk1.8.0_191
